version: "3.9"

services:
  app:
    build: .
    container_name: subscription_app
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: ["/app/entrypoint.sh"]

  db:
    image: postgres:15
    container_name: subscription_db
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

